
version: '3'
services:
  # DataDog
  my_datadog_container:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=3ec06417f567569f0b2121d3ef306741
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_TAGS=env:${ENVIRONMENT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  # Front end
  game_client:
    image: skulipardus/hgop-lucky21-front-end:${GIT_COMMIT}
    ports:
    - '4000:4000'
    depends_on:
    - game_api
    environment:
      PORT: 4000
      API_PORT: 3000
      API_URL: ${API_URL}
  # API
  game_api:
    image: skulipardus/hgop-api:${GIT_COMMIT}
    # image: skulipardus/hgop-api:testnewapi
    ports:
    - '3000:3000'
    depends_on:
    - game_database_container
    environment:
      PORT: 3000
      POSTGRES_HOST: 'game_database_container'
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root123'
  # Postgres image to achieve functionality of API
  game_database_container:
    image: postgres
    environment:
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root123'