
version: '3'
services:
  my_item_repository:
    image: skulipardus/hgop:${GIT_COMMIT}
    ports:
    - '3000:3000'
    depends_on:
    - item_db_container
    environment:
      POSTGRES_DB: 'item_db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root123'
      PORT: 3000
  # Postgres image to achieve functionality of API
  item_db_container:
    image: postgres
    environment:
      POSTGRES_DB: 'item_db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root123'
      PORT: 3000